version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: panzerknaker
      POSTGRES_PASSWORD: 1212
      POSTGRES_DB: turistbusdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  turistbus_service:
    restart: on-failure
    container_name: turistbus_service
    build: ./turistbus_service/
    ports:
      - "8000:80"
    depends_on:
      - db

  ticket_service:
    restart: on-failure
    container_name: ticket_service
    build: ./ticket_service/
    ports:
      - "8001:80"
    depends_on:
      - db